baseurl = "https://www.varyvoda.com"
title = "Igor Varyvoda"
theme = "hugo-coder"
locale = "en"
defaultcontentlanguage = "en"
pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
disableKinds = ["taxonomy", "term"]

disqusShortname = "varyvoda"

[outputs]
  home = ["HTML", "RSS", "Markdown"]
  section = ["HTML", "RSS", "Markdown"]
  page = ["HTML", "Markdown"]
[markup.goldmark.renderer]
  unsafe= true
[markup.highlight]
  style = "catppuccin-mocha"

[params]
  author = "Igor Varyvoda"
  info = "Product Builder and Operator"
  description = "Igor Varyvoda builds and operates internet products. He grew his first commercial website to roughly 50,000 daily visitors, led cross-functional teams and growth at Magic Toolbox and Sirv, and created Sirv Studio."
  avatarurl = "https://iantiark.sirv.com/pic.jpg?w=300"
  #gravatar = "igor@varyvoda.com"

  footercontent = ""
  hideFooter = false
  hideCredits = false
  hideCopyright = false
  since = 2025

  enableTwemoji = true

  colorScheme = "dark"
  hidecolorschemetoggle = true

  customCSS = []
  customSCSS = []
  customJS = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/igorvaryvoda"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/igorvaryvoda/"
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/igorvaryvoda/"
[[params.social]]
  name = "Email"
  weight = 2
  url = "mailto:igor@varyvoda.com"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
[[menu.main]]
  name = "Projects"
  weight = 3
  url = "projects/"
[[menu.main]]
  name = "Contact me"
  weight = 3
  url = "contact/"
